repos:
  - hooks:
      - id: black
    repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.13.2
  - hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-mock, lxml-stubs]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
